export const UPDATE_ENGINE_CONFIGURATION = 'UPDATE_ENGINE_CONFIGURATION';
export const UPDATE_ENGINE_INSTANCE = 'UPDATE_ENGINE_INSTANCE';
export const UPDATE_WORKFLOW_STATE = 'UPDATE_WORKFLOW_STATE';
